[package]
name = "aws_config_generator"
version = "0.1.0"
authors = ["Alan Jenkins <alan.james.jenkins@gmail.com>"]
edition = "2021"

[lib]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.46.0"
aws-sdk-organizations = "0.16.0"
aws-sdk-sts = "0.17.0"
clap = "3.2"
dirs = "4.0"
lazy_static = "1.4.0"
tera = "1.16.0"
tokio = { version = "1.20", features = ["full"] }
toml = "0.5"
